<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/composer' . '/autoload_real.php';
require_once __DIR__ . '/lib/hades/hades-sql' . '/core.php';
require_once __DIR__ . '/lib/hades/hades-sql' . '/crud.php';
require_once __DIR__ . '/lib/hades' . '/bot.php';

return ComposerAutoloaderInit26bcae5a5544a0e55f382d5d7fde11b8::getLoader();